#!/bin/sh
 
br0_exist_flag=`ifconfig|grep -ci "br0"`
if [ $br0_exist_flag -eq 0 ];then
	sudo brctl addbr br0
	sudo ifconfig br0 192.168.80.100 netmask 255.255.255.0 up
	sudo route add -net 192.168.80.0 netmask 255.255.255.0 br0
	sudo route add default gw 192.168.80.1 br0
fi
 
sudo tunctl -t $1 -u root
sudo ifconfig $1 up
sudo brctl addif br0 $1